version: '3'

services:
  app:

    # build: royatali/fastapi
    image: royatali/fastapi
    depends_on:
      - db
    ports:
      - "8000:8000"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
     
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    volumes:
      - postgres-db:/var/lib/postgresql/data

    ports:
      - "5432:5432"

volumes:
    postgres-db: 