name: Build and Deploy Code

on: [push, pull_request]
defaults:
  run:
    working-directory: backend
jobs:
  job1:
    environment:
      name: testing

    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}
      EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4

      - name: Install python version 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install all dependecies
        run: pip install -r requirements.txt

      - name: test with pytest
        run: |
          pip install pytest
          pytest
